/**
 * Interop regression test: tools-sealed -> reader-verified, fully offline.
 *
 * Fixture provenance (2026-07-22, feat/version-truth-083):
 * - Artifact: edm-spec examples/example-full-profile.json (spec v0.8.3,
 *   meta.version "0.8.3")
 * - Sealed with the sibling ddna-tools CLI (`ddna seal`) using a THROWAWAY
 *   local Ed25519 key generated by `ddna keygen`. The private key was never
 *   committed anywhere; the envelope embeds only the did:key (public key)
 *   and the Ed25519 signature, so the fixture is self-contained and safe.
 * - ddna_header.edm_version and edm_payload.meta.version are frozen at the
 *   sealing-time spec version. As the spec advances this becomes a
 *   HISTORICAL envelope — the reader must keep accepting it (readers are
 *   version-agnostic: edm_version is recorded, not gated). Do NOT update
 *   this fixture to chase the current spec version; add new fixtures.
 *
 * This test is the offline-verifier property guard (the open-standard
 * claim): a regression here is a release blocker. Verification of did:key
 * envelopes must require NO network — see the conformance suite and the
 * absence of any http/https/dns/fetch import on the verify path.
 */

import { describe, test, expect, beforeAll, afterAll } from 'vitest';
import { readFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import http from 'node:http';
import https from 'node:https';
import { verify, verifySync } from '../src/lib/verify.js';
import { inspectEnvelope, validateStructure } from '../src/lib/inspect.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const FIXTURE = join(__dirname, 'fixtures', 'interop-tools-sealed-full.ddna');

const envelope = JSON.parse(readFileSync(FIXTURE, 'utf-8'));

// Trap ALL Node network entry points for the duration of this suite.
// If verification touches the network in any way, the test fails loudly.
// (globalThis.fetch, http.request, https.request cover fetch/undici and
// the classic http stack; did:key resolution is pure local decoding.)
const trapped: string[] = [];
let origFetch: typeof globalThis.fetch;
let origHttpRequest: typeof http.request;
let origHttpsRequest: typeof https.request;

beforeAll(() => {
  origFetch = globalThis.fetch;
  origHttpRequest = http.request;
  origHttpsRequest = https.request;
  globalThis.fetch = ((...args: unknown[]) => {
    trapped.push(`fetch(${String(args[0])})`);
    throw new Error('NETWORK CALL DURING OFFLINE VERIFY');
  }) as typeof globalThis.fetch;
  (http as { request: unknown }).request = (...args: unknown[]) => {
    trapped.push(`http.request(${String(args[0])})`);
    throw new Error('NETWORK CALL DURING OFFLINE VERIFY');
  };
  (https as { request: unknown }).request = (...args: unknown[]) => {
    trapped.push(`https.request(${String(args[0])})`);
    throw new Error('NETWORK CALL DURING OFFLINE VERIFY');
  };
});

afterAll(() => {
  globalThis.fetch = origFetch;
  http.request = origHttpRequest;
  https.request = origHttpsRequest;
});

describe('tools-sealed -> reader-verified interop (offline)', () => {
  test('structure validates', () => {
    const result = validateStructure(envelope);
    expect(result.valid, result.errors.join('; ')).toBe(true);
  });

  test('inspection reads the sealing-time schema version', () => {
    const result = inspectEnvelope(envelope);
    expect(result.structureValid).toBe(true);
    // Self-consistency: header edm_version matches the payload meta.version
    // stamped by the sealer (both frozen at sealing time).
    expect(result.schemaVersion).toBe(envelope.edm_payload.meta.version);
  });

  test('verify() accepts the tools-sealed envelope with zero network calls', async () => {
    const result = await verify(envelope);
    expect(result.valid, result.reason).toBe(true);
    expect(result.verificationMethod).toBe(envelope.proof.verificationMethod);
    expect(trapped, `network calls observed: ${trapped.join(', ')}`).toHaveLength(0);
  });

  test('verifySync() accepts the tools-sealed envelope (did:key, offline)', () => {
    const result = verifySync(envelope);
    expect(result.valid, result.reason).toBe(true);
    expect(trapped, `network calls observed: ${trapped.join(', ')}`).toHaveLength(0);
  });

  test('tampered payload is rejected', async () => {
    const tampered = JSON.parse(readFileSync(FIXTURE, 'utf-8'));
    tampered.edm_payload.meta.owner_user_id = 'attacker';
    const result = await verify(tampered);
    expect(result.valid).toBe(false);
  });
});
